### PR TITLE
#531, strip() excessive spaces when rendered plugins return ones

### PR DESCRIPTION
**Pull request by sq9mev**
#531 remove excessive spaces

### CODE REVIEW

**Comment by jrief** [comment]
In my optionion such a stripping shoulg go unto the passed in `output_func`.

**Comment by FinalAngel** [comment]
Thank you for the PR @sq9mev, at first sight that seems fine to me @jrief, could you elaborate further?

@sq9mev would you also be able to add a test and changelog entry for this?

**Comment by jrief** [comment]
I would strip the string inside the function [_strip_plugin_content()](https://github.com/django-cms/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/utils.py#L125). This is so that if needed, it's easier to override.

**Comment by DmytroLitvinov** [comment]
@vinitkumar , can be closed because of https://github.com/django-cms/djangocms-text-ckeditor/pull/597

**Pull request closed without merging**
