### PR TITLE
Add Django 3.2 to tests

### LINKED ISSUE #582: Add official support for Django 3.2

### PR DESCRIPTION
**Pull request by DmytroLitvinov**
Closes #582

### CODE REVIEW

**Comment by DmytroLitvinov** [comment]
Hi @victor-yunenko,
Could you please review it and approve CI trigger and merge in case if there is no problem with it?

**Comment by DmytroLitvinov** [comment]
Hi @marksweb ,
Could you please rerun CI? Seems like after merging latest changes to `master` branch it should be ok for now.

**Comment by marksweb** [comment]
@DmytroLitvinov if you merge master into your branch it should see the python tests pass.

**Comment by marksweb** [comment]
Absolutely. Thank you @DmytroLitvinov

**Comment by vinitkumar** [comment]
@DmytroLitvinov Please rebase master into your branch. We just fixed the CI on the master now, so your tests from this branch should be able to run as well.

**Comment by marksweb** [comment]
@DmytroLitvinov I've left a couple of comments on this, the change log title and dropping EOL python from tests.

Could you take a look please & rebase master as we've just upgraded the gulp pipeline.

**Review by marksweb — APPROVED** [review]

**Comment by marksweb** [comment]
The test suite doesn't support django 3.2. So although I've merged this, when I added 3.2 to the github workflow it failed. This is likely related to a lack of 3.2 support in django-app-helper.

I've raised an issue already on there after I was looking at updates to django-filer. But it seems nephila aren't maintaining their packages anymore; https://github.com/nephila/django-app-helper/issues/204

**Pull request merged**
