### PR TITLE
504 copy paste plugins inside ckeditor refer to same instance

### PR DESCRIPTION
**Pull request by nichoski**
This is fixing a severe bug caused by [pull request 569](https://github.com/django-cms/djangocms-text-ckeditor/pull/569). In pull request 569, after the referenced plugin is copied  successfully, the post_copy method is removing the other child plugins of the plugin we are pasting into, because the other child plugins are not inside the plugins_ziplist provided in the arguments of the post_copy method. This fix is including the existing plugins as well, so they are not touched by the post_copy method.

### CODE REVIEW

**Review by vinitkumar — APPROVED** [review]
Looks good to me!

**Comment by gabrielcandrade** [comment]
Looks Good! :+1:

**Comment by marksweb** [comment]
@nichoski do you think, given what we've seen happen here, that a test case could be written for this?

**Comment by nichoski** [comment]
@marksweb yes, it's the least I could do. I just added a test case to this.

**Review by marksweb — APPROVED** [review]

**Comment by nichoski** [comment]
This was merged into master, but I don't see it in any of the releases. Is this planned to be added in a new release? Or is it already added and I have issues finding it?

**Pull request merged**
