### PR TITLE
Fix: Allow double clicks to propagate.

### LINKED ISSUE #675: Double clicking an inserted link doesn't opens the edit popup in the latest version
If you have added a link in the editor and if you try to edit it by double clicking. The edit popup of link doesn't appears. Please confirm, it was working fine until we upgraded to 5.1.5 version

### PR DESCRIPTION
**Pull request by fsbraun**
Fixes #675 

Since the introduction of inline editing, double-clicks had been swallowed. Now they propagate.

@vipulnarang95 Can you please confirm this PR fixes your issue?

### CODE REVIEW

**Comment by vipulnarang95** [comment]
Hi @fsbraun , it works well, When are you merging this pr?

**Comment by fsbraun** [comment]
@vipulnarang95 I was hoping for your feedback if the PR solves your issue. You can install and test it using 
```
pip install git+https://github.com/fsbraun/djangocms-text-ckeditor@fix/double-click
```

Once I get your confirmation, I can have it reviewed, merged, and released.

**Comment by vipulnarang95** [comment]
Hi @fsbraun , I confirm it is working fine

**Comment by vipulnarang95** [comment]
@fsbraun Can you also release this?

**Comment by vipulnarang95** [comment]
I am not able to see on divio cloud? Is there a separate release for this?

**Comment by vipulnarang95** [comment]
Which version it is? 5.1.6?

**Pull request merged**
